# Dockerfile
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements-streamlit.txt /app/

# Install any dependencies
RUN pip install --no-cache-dir -r requirements-streamlit.txt

# Copy the content of the local src directory to the working directory
COPY . /app/

# Streamlit runs on port 8501 by default, so expose it
EXPOSE 8501

# Command to run the app
CMD ["streamlit", "run", "app.py", "--server.port=8501"]

